"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-05

Written by hand rather than autogenerated, so the schema is a deliberate
artefact and the migration always runs.

Shape follows REPORT.md §8: `observation` is append-only and
authoritative; `lexeme`, `variant`, `guard`, `binding` and `phonetic_key` are a
rebuildable projection over it; `adjudication` is write-once telemetry.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ------------------------------------------------------------------ #
    # Evidence — append only. Truncating this table is a full reset.
    # ------------------------------------------------------------------ #
    op.create_table(
        "observation",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("source", sa.String(24), nullable=False),
        sa.Column("polarity", sa.String(16), nullable=False, server_default="supports"),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("before_form", sa.Text()),
        sa.Column("after_form", sa.Text(), nullable=False),
        sa.Column("scope", sa.String(16), nullable=False, server_default="global"),
        sa.Column("scope_ref", sa.String(200)),
        sa.Column("utterance_id", sa.String(64)),
        sa.Column("surrounding_text", sa.Text()),
        sa.Column("lexeme_id", sa.String(36)),
        sa.Column("phonetic_distance", sa.Float()),
        # NULL = not yet judged, 0 = rejected as a non-phonetic rewrite.
        sa.Column("accepted", sa.Boolean()),
        sa.Column("note", sa.Text()),
        sa.Column("meta_json", sa.Text()),
    )
    op.create_index("ix_observation_at", "observation", ["at"])
    op.create_index("ix_observation_lexeme", "observation", ["lexeme_id"])
    op.create_index("ix_observation_source", "observation", ["source"])

    # ------------------------------------------------------------------ #
    # Projection — always rebuildable from `observation`.
    # ------------------------------------------------------------------ #
    op.create_table(
        "lexeme",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("canonical", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(24), nullable=False),
        # The standing instruction, in the user's own words. Injected verbatim
        # into the formatting prompt.
        sa.Column("instruction", sa.Text()),
        sa.Column("parent_id", sa.String(36), sa.ForeignKey("lexeme.id", ondelete="SET NULL")),
        sa.Column("conf_alpha", sa.Float(), nullable=False, server_default="1.0"),
        sa.Column("conf_beta", sa.Float(), nullable=False, server_default="1.0"),
        sa.Column("state", sa.String(16), nullable=False, server_default="proposed"),
        sa.Column("learning_enabled", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("first_seen", sa.DateTime(timezone=True)),
        sa.Column("last_used", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_lexeme_state", "lexeme", ["state"])
    op.create_index("ix_lexeme_canonical", "lexeme", ["canonical"])

    op.create_table(
        "variant",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("lexeme_id", sa.String(36), sa.ForeignKey("lexeme.id", ondelete="CASCADE"), nullable=False),
        sa.Column("form", sa.Text(), nullable=False),
        sa.Column("form_norm", sa.Text(), nullable=False),  # casefolded, collapsed
        # observed > declared > generated. Drives how much a match is trusted.
        sa.Column("provenance", sa.String(16), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("last_seen", sa.DateTime(timezone=True)),
        sa.Column("scope", sa.String(16), nullable=False, server_default="global"),
        sa.Column("scope_ref", sa.String(200)),
        sa.UniqueConstraint("lexeme_id", "form_norm", "scope", "scope_ref", name="uq_variant_form"),
    )
    op.create_index("ix_variant_form_norm", "variant", ["form_norm"])

    op.create_table(
        "guard",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("lexeme_id", sa.String(36), sa.ForeignKey("lexeme.id", ondelete="CASCADE"), nullable=False),
        sa.Column("kind", sa.String(32), nullable=False),
        sa.Column("payload_json", sa.Text(), nullable=False, server_default="{}"),
        sa.Column("created_by_observation_id", sa.String(36)),
        sa.Column("note", sa.Text()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_guard_lexeme", "guard", ["lexeme_id"])

    op.create_table(
        "binding",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("lexeme_id", sa.String(36), sa.ForeignKey("lexeme.id", ondelete="CASCADE"), nullable=False),
        sa.Column("scope", sa.String(16), nullable=False),
        sa.Column("scope_ref", sa.String(200)),
        sa.UniqueConstraint("lexeme_id", "scope", "scope_ref", name="uq_binding"),
    )

    op.create_table(
        "phonetic_key",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("lexeme_id", sa.String(36), sa.ForeignKey("lexeme.id", ondelete="CASCADE"), nullable=False),
        sa.Column("algo", sa.String(32), nullable=False),
        sa.Column("key", sa.String(64), nullable=False),
        sa.Column("source_form", sa.Text(), nullable=False),
    )
    op.create_index("ix_phonetic_key_lookup", "phonetic_key", ["algo", "key"])

    op.create_table(
        "edge",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("a_id", sa.String(36), sa.ForeignKey("lexeme.id", ondelete="CASCADE"), nullable=False),
        sa.Column("b_id", sa.String(36), sa.ForeignKey("lexeme.id", ondelete="CASCADE"), nullable=False),
        # alias | cooccurs | conflicts
        sa.Column("rel", sa.String(16), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False, server_default="1.0"),
        sa.Column("observed_count", sa.Integer(), nullable=False, server_default="0"),
        sa.UniqueConstraint("a_id", "b_id", "rel", name="uq_edge"),
    )
    op.create_index("ix_edge_a", "edge", ["a_id"])

    op.create_table(
        "evidence_link",
        sa.Column("lexeme_id", sa.String(36), sa.ForeignKey("lexeme.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("observation_id", sa.String(36), primary_key=True),
        sa.Column("delta_alpha", sa.Float(), nullable=False, server_default="0.0"),
        sa.Column("delta_beta", sa.Float(), nullable=False, server_default="0.0"),
    )

    op.create_table(
        "tombstone",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("reason", sa.String(32), nullable=False),
        sa.Column("canonical", sa.Text(), nullable=False),
        sa.Column("match_forms_json", sa.Text(), nullable=False, server_default="[]"),
        sa.Column("source_lexeme_id", sa.String(36)),
        sa.Column("replacement_lexeme_id", sa.String(36)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    # ------------------------------------------------------------------ #
    # Telemetry — one row per call, including the ones where nothing happened.
    # This table is the "make failures inspectable" requirement.
    # ------------------------------------------------------------------ #
    op.create_table(
        "adjudication",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("utterance_id", sa.String(64)),
        sa.Column("app", sa.String(200)),
        sa.Column("persona", sa.String(200)),
        sa.Column("asr_text", sa.Text(), nullable=False),
        sa.Column("formatted_text", sa.Text(), nullable=False),
        sa.Column("output_text", sa.Text(), nullable=False),
        sa.Column("gate_passed", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("intervened", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("verifier_rejected", sa.Boolean(), nullable=False, server_default=sa.false()),
        # Full candidate set with every policy outcome. The audit trail.
        sa.Column("resolutions_json", sa.Text(), nullable=False, server_default="[]"),
        sa.Column("primary_reason", sa.String(48)),
        sa.Column("llm_calls", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("completion_tokens", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("cost_paise", sa.Float(), nullable=False, server_default="0.0"),
        sa.Column("latency_ms", sa.Float(), nullable=False, server_default="0.0"),
        # Observation-log high-water mark, so the memory state at decision time
        # can be reconstructed exactly.
        sa.Column("observation_watermark", sa.Integer(), nullable=False, server_default="0"),
    )
    op.create_index("ix_adjudication_at", "adjudication", ["at"])
    op.create_index("ix_adjudication_reason", "adjudication", ["primary_reason"])


def downgrade() -> None:
    for table in (
        "adjudication",
        "tombstone",
        "evidence_link",
        "edge",
        "phonetic_key",
        "binding",
        "guard",
        "variant",
        "lexeme",
        "observation",
    ):
        op.drop_table(table)
